@route = dividas

# @name getDividasByDevedor
GET {{baseUrl}}/{{route}}/devedor/2

###
# @name postDivida
POST {{baseUrl}}/{{route}}
Content-Type: application/json

{
  "devedorId": 3,
  "data": "2025-10-11",
  "descricao": "Fatura do cartão de crédito",
  "valor": 1763.96,
  "observacao": "Devolver para o Cofrinho Viagens"
}

###
# @name postDividaPagamento
POST {{baseUrl}}/{{route}}/pagamentos
Content-Type: application/json

{
  "dividaId": 3,
  "data": "2026-02-06",
  "valor": 150.00
}